#!/usr/bin/env python3
"""
WalletBench Lead Standup — runs every 5 hours
Reads board state, identifies blockers, creates unblocking tasks,
rotates providers, reports status to Samuel.
"""
import subprocess
import json
import os
from datetime import datetime

BOARD_FILE = "/tmp/wb_board_status.json"
REPORT_FILE = "/home/ops/code/lattice-nine-vault/projects/walletbench/STATUS-REPORT.md"

def run(cmd):
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return result.stdout.strip()

def log(msg):
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    print(f"[{ts}] {msg}")

def get_board_state():
    """Get current kanban state."""
    output = run("hermes kanban list --format json 2>/dev/null || echo '[]'")
    try:
        return json.loads(output)
    except:
        return []

def get_failed_tasks(tasks):
    """Identify blocked/failed tasks that need attention."""
    problematic = []
    for t in tasks:
        status = t.get("status", "")
        if status in ["blocked", "failed", "crashed"]:
            problematic.append(t)
        elif status == "running":
            # Check if running too long (> 2h)
            # (would need created_at timestamp parsing)
            pass
    return problematic

def create_unblocking_task(blocked_task):
    """Create a follow-up task to unblock."""
    task_id = blocked_task["id"]
    title = blocked_task["title"]
    assignee = blocked_task.get("assignee", "wb-lead")
    
    new_title = f"UNBLOCK: {title[:40]}"
    body = f"Task {task_id} is blocked. Investigate logs with: hermes kanban log {task_id}"
    
    cmd = f"hermes kanban create '{new_title}' --assignee wb-lead --body '{body}' --workspace scratch"
    result = run(cmd)
    log(f"Created unblock task for {task_id}: {result}")

def generate_report(tasks, problematic):
    """Generate a markdown report for Samuel."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    
    report = f"""# WalletBench Status Report — {now}

## Board Summary

| Status | Count |
|--------|-------|
| Done | {sum(1 for t in tasks if t.get('status') == 'done')} |
| Ready | {sum(1 for t in tasks if t.get('status') == 'ready')} |
| Running | {sum(1 for t in tasks if t.get('status') == 'running')} |
| Blocked/Failed | {len(problematic)} |
| Todo | {sum(1 for t in tasks if t.get('status') == 'todo')} |

## 🚨 Blockers Requiring Attention

"""
    
    if problematic:
        for t in problematic:
            report += f"- **{t['id']}** | {t.get('assignee', 'unknown')} | {t['status']} | {t['title'][:50]}\n"
            report += f"  - Check: `hermes kanban log {t['id']}`\n"
    else:
        report += "_No blockers. Pipeline flowing._\n"
    
    report += f"""
## ▶ Ready to Dispatch

"""
    ready = [t for t in tasks if t.get("status") == "ready"]
    if ready:
        for t in ready:
            report += f"- **{t['id']}** | {t.get('assignee', 'unknown')} | {t['title'][:50]}\n"
    else:
        report += "_No ready tasks. Waiting for dependencies._\n"
    
    report += """
## Provider Status

"""
    # Check ZAI status file
    if os.path.exists("/tmp/wb_zai_status.json"):
        with open("/tmp/wb_zai_status.json") as f:
            zai = json.load(f)
        report += f"- **ZAI**: {'✅ Available' if zai.get('available') else '❌ Rate Limited'}\n"
        report += f"- Last checked: {zai.get('last_check', 'unknown')}\n"
    else:
        report += "- **ZAI**: glm-5.2 primary (fallback chain: kimi-k2.6 → step-3.7-free)\n"
    
    report += """
## Next Actions

1. Run `hermes kanban dispatch` to spawn ready tasks
2. Review blockers above and create unblocking tasks if needed
3. Check token burn with `hermes kanban stats`

---
*Auto-generated by wb-lead standup script*
"""
    
    return report

def main():
    log("Starting lead standup...")
    
    # 1. Get board state
    tasks = get_board_state()
    log(f"Board has {len(tasks)} tasks")
    
    # 2. Identify blockers
    problematic = get_failed_tasks(tasks)
    if problematic:
        log(f"Found {len(problematic)} problematic tasks")
        for t in problematic:
            log(f"  - {t['id']}: {t['title'][:40]} ({t['status']})")
            # Create unblock task for each
            create_unblocking_task(t)
    
    # 3. Generate report (provider rotation handled by fallback chain automatically)
    
    # 4. Generate report
    report = generate_report(tasks, problematic)
    with open(REPORT_FILE, "w") as f:
        f.write(report)
    log(f"Report written to {REPORT_FILE}")
    
    # 5. Also append to vault
    vault_path = "/home/ops/code/lattice-nine-vault/projects/walletbench/STATUS-REPORT.md"
    with open(vault_path, "w") as f:
        f.write(report)
    log("Report synced to vault")
    
    log("Standup complete.")

if __name__ == "__main__":
    main()
